name: Deploy Charts to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject CSS to hide Chart Studio links
        run: |
          chmod +x .github/scripts/inject-css.sh
          .github/scripts/inject-css.sh

      - name: Generate index page
        run: |
          chmod +x .github/scripts/generate-index.sh
          .github/scripts/generate-index.sh

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'charts'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
